#     _    _              _ ___ _                  #
#    / \  | | ____ _ _ __(_)_ _| |_ ___ _ __ ___   #
#   / _ \ | |/ / _` | '__| || || __/ _ \ '_ ` _ \  #
#  / ___ \|   < (_| | |  | || || ||  __/ | | | | | #
# /_/   \_\_|\_\__,_|_|  |_|___|\__\___|_| |_| |_| #

###############################
#      AkariItem  Config      #
###############################

###########
# Options #
###########

# 全局设置
Options:
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false